// Load the wasm JS glue generated by emscripten
// Copy colorgrid.{js,wasm} into frontend/public/ so Vite can serve them statically.
const scriptUrl = new URL('/color_contrast_wasm.js', import.meta.url).href;
const createModule = (await import(scriptUrl)).default;

const dimInput = document.getElementById('dim') as HTMLInputElement;
const itersInput = document.getElementById('iters') as HTMLInputElement;
const runBtn = document.getElementById('run') as HTMLButtonElement;
const statusEl = document.getElementById('status') as HTMLSpanElement;
const canvas = document.getElementById('grid') as HTMLCanvasElement;
const ctx = canvas.getContext('2d')!;

function drawGridRGB(rgb: Uint8Array, dim: number) {
  const cellPx = Math.floor(Math.min(canvas.width, canvas.height) / dim);
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  let k = 0;
  for (let y = 0; y < dim; y++) {
    for (let x = 0; x < dim; x++) {
      const r = rgb[k++], g = rgb[k++], b = rgb[k++];
      ctx.fillStyle = `rgb(${r},${g},${b})`;
      ctx.fillRect(x * cellPx, y * cellPx, cellPx, cellPx);
    }
  }
}

runBtn.onclick = async () => {
  const dim = Math.max(2, Math.min(50, parseInt(dimInput.value || '5', 10)));
  const iters = Math.max(1, parseInt(itersInput.value || '1000', 10));
  statusEl.textContent = 'Loading WASM...';

  const Module = await createModule();
  statusEl.textContent = 'Running...';

  // Call C++ function; returns std::vector<uint8_t> → typed array
const result = Module.compute_grid(dim,iters);
  drawGridRGB(result.colors, dim);

  statusEl.textContent = `Done. Best of ${iters} iterations.`;
};
